// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhzapwstxrsiuaghteag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoemFwd3N0eHJzaXVhZ2h0ZWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDk1NDgsImV4cCI6MjA2NjU4NTU0OH0.ItawheM5XhPQZg78nNxXHe0Izc3q2Rc79zHO5CL6b84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);